"""Regression gate: committed fixtures must stay openable.

These fixtures were generated by tools/make_fixtures.py with a published
fake passphrase. If any of these tests fail, a format or crypto change has
broken backward compatibility - the most serious regression this project
can have (FORMAT.md). Never delete or weaken these tests.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import keepsafe.crypto as crypto
from keepsafe.format import open_vault_file
from keepsafe.model import entries_from_payload

FIXTURES = Path(__file__).resolve().parent / "fixtures"
MANIFEST = json.loads((FIXTURES / "manifest.json").read_text(encoding="utf-8"))
PUBLIC_PASSPHRASE = MANIFEST["passphrase_is_public"]


def test_fixture_files_exist_and_are_marked_fake():
    assert (FIXTURES / "FIXTURES-ARE-FAKE.txt").is_file()
    assert (FIXTURES / MANIFEST["file"]).is_file()


def test_manifest_version_matches_shipped_format():
    # When this fails, you have bumped the format without generating and
    # committing a new fixture + migration path.
    assert MANIFEST["format_version"] == crypto.FORMAT_VERSION


def test_current_release_opens_v1_fixture_with_published_passphrase():
    blob = (FIXTURES / MANIFEST["file"]).read_bytes()
    header, payload = open_vault_file(blob, PUBLIC_PASSPHRASE)
    assert header.version == 1
    assert header.kdf_type == crypto.KDF_TYPE_ARGON2ID
    entries = {e.name: e for e in entries_from_payload(payload)}
    assert sorted(entries) == MANIFEST["expected_names"]
    for name, expected_secret in MANIFEST["expected_secrets"].items():
        assert entries[name].secret == expected_secret
        assert entries[name].username == MANIFEST["expected_usernames"][name]
    # Custom fields survive exactly:
    mail = entries["example/web/mail"]
    secret_fields = [f for f in mail.fields if f.secret]
    assert secret_fields and secret_fields[0].value == "FAKE-RECOVERY-0001"
    plain = [f for f in mail.fields if not f.secret]
    assert plain and plain[0].value == "test-1"


def test_fixture_rejects_wrong_passphrase():
    from keepsafe.errors import UnlockFailed

    blob = (FIXTURES / MANIFEST["file"]).read_bytes()
    with pytest.raises(UnlockFailed):
        open_vault_file(blob, "wrong-passphrase-for-fixture")


def test_fixture_tamper_refused_header_and_payload():
    from keepsafe.errors import UnlockFailed

    blob = bytearray((FIXTURES / MANIFEST["file"]).read_bytes())
    blob[len(blob) // 2] ^= 0x01
    with pytest.raises(UnlockFailed):
        open_vault_file(bytes(blob), PUBLIC_PASSPHRASE)
