"""Regenerate committed test fixtures for Keepsafe.

Every fixture vault here is generated from OBVIOUSLY FAKE data with a
PUBLISHED test passphrase (below). Nothing in these files is a real
credential; they exist so the regression suite can prove that newer
versions of Keepsafe still open vaults written by every earlier released
format version (see FORMAT.md: a vault that cannot be opened by a later
version is total data loss).

Policy:
- One fixture file per released format version: vault-v<FORMAT_VERSION>.kpsf.
- Regenerate ONLY when intentionally producing a new format version or when
  the fixture manifest changes; commit both file and manifest together.
- The passphrase below is public on purpose. Never replace it with a real
  one; never commit a real vault under tests/fixtures/.

Usage:  python tools/make_fixtures.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from keepsafe import crypto, model  # noqa: E402
from keepsafe.format import build_vault_file  # noqa: E402

# Published, deliberately fake test passphrase.
FIXTURE_PASSPHRASE = "fixture-passphrase-0001"

FIXTURE_ENTRIES = [
    {
        "name": "example/web/mail",
        "username": "someone@example.com",
        "secret": "fake-secret-DO-NOT-USE-1",
        "url": "https://mail.example.com",
        "notes": "Fixture entry. The data in this vault is invented.",
        "tags": ["fixture", "web"],
        "fields": [
            {"key": "recovery_code", "value": "FAKE-RECOVERY-0001", "secret": True},
            {"key": "region", "value": "test-1", "secret": False},
        ],
    },
    {
        "name": "example/dev/api",
        "username": "svc-fixture",
        "secret": "fake-secret-DO-NOT-USE-2",
        "url": "",
        "notes": "",
        "tags": ["fixture"],
        "fields": [],
    },
]


def utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def build_payload() -> dict:
    entries = []
    for raw in FIXTURE_ENTRIES:
        e = model.Entry(
            name=raw["name"], username=raw["username"], secret=raw["secret"],
            url=raw["url"], notes=raw["notes"], tags=list(raw["tags"]),
            created=utc_iso(), updated=utc_iso(),
            fields=[model.Field(key=f["key"], value=f["value"], secret=f["secret"])
                    for f in raw["fields"]],
        )
        entries.append(e)
    return model.payload_from_entries(entries)


def main() -> int:
    fx_dir = ROOT / "tests" / "fixtures"
    fx_dir.mkdir(parents=True, exist_ok=True)
    marker = fx_dir / "FIXTURES-ARE-FAKE.txt"
    marker.write_text(
        "Everything in this directory was generated by tools/make_fixtures.py\n"
        f"from invented data with the published test passphrase '{FIXTURE_PASSPHRASE}'.\n"
        "These are NOT real credentials. Do not store real secrets here, ever.\n",
        encoding="utf-8",
    )

    payload = build_payload()
    data, header = build_vault_file(FIXTURE_PASSPHRASE, payload)
    out = fx_dir / f"vault-v{crypto.FORMAT_VERSION}.kpsf"
    out.write_bytes(data)

    manifest = {
        "file": out.name,
        "format_version": crypto.FORMAT_VERSION,
        "passphrase_is_public": FIXTURE_PASSPHRASE,
        "note": "generated fake data; see FIXTURES-ARE-FAKE.txt",
        "expected_names": sorted(e["name"] for e in FIXTURE_ENTRIES),
        "expected_secrets": {e["name"]: e["secret"] for e in FIXTURE_ENTRIES},
        "expected_usernames": {e["name"]: e["username"] for e in FIXTURE_ENTRIES},
    }
    (fx_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {out} ({len(data)} bytes), manifest.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
